ASR_config: Utils/ASR/config_ko.yml
ASR_path: Utils/ASR/epoch_00200.pth
F0_path: Utils/JDC/bst.t7
PLBERT_dir: Utils/PLBERT/
batch_size: 4
data_params:
  OOD_data: /workspace/ai/jhyoo/TTS-DATASET/StyleTTS2/Result/multi/case1/OOD_texts.txt
  min_length: 50
  root_path: /workspace/ai/jhyoo/TTS-DATASET/StyleTTS2/Result/multi/case1
  train_data: /workspace/ai/jhyoo/TTS-DATASET/StyleTTS2/Result/multi/case1/train_list.txt
  val_data: /workspace/ai/jhyoo/TTS-DATASET/StyleTTS2/Result/multi/case1/valid_list.txt
device: cuda
epochs_1st: 200
epochs_2nd: 100
first_stage_path: /workspace/ai/jhyoo/StyleTTS2/Models/Multi/0218_TEST/epoch_1st_00070.pth
load_only_params: false
log_dir: Models/Multi/0218_TEST
log_interval: 10
loss_params:
  TMA_epoch: 50
  diff_epoch: 20
  joint_epoch: 50
  lambda_F0: 1.0
  lambda_ce: 20.0
  lambda_diff: 1.0
  lambda_dur: 1.0
  lambda_gen: 1.0
  lambda_mel: 5.0
  lambda_mono: 1.0
  lambda_norm: 1.0
  lambda_s2s: 1.0
  lambda_slm: 1.0
  lambda_sty: 1.0
max_len: 600
model_params:
  decoder:
    gen_istft_hop_size: 5
    gen_istft_n_fft: 20
    resblock_dilation_sizes:
    - - 1
      - 3
      - 5
    - - 1
      - 3
      - 5
    - - 1
      - 3
      - 5
    resblock_kernel_sizes:
    - 3
    - 7
    - 11
    type: istftnet
    upsample_initial_channel: 512
    upsample_kernel_sizes:
    - 20
    - 12
    upsample_rates:
    - 10
    - 6
  diffusion:
    dist:
      estimate_sigma_data: true
      mean: -3.0
      sigma_data: 0.27155903965709327
      std: 1.0
    embedding_mask_proba: 0.1
    transformer:
      head_features: 64
      multiplier: 2
      num_heads: 8
      num_layers: 3
  dim_in: 64
  dropout: 0.2
  hidden_dim: 512
  max_conv_dim: 512
  max_dur: 50
  multispeaker: true
  n_layer: 3
  n_mels: 80
  n_token: 179
  slm:
    hidden: 768
    initial_channel: 64
    model: microsoft/wavlm-base-plus
    nlayers: 13
    sr: 16000
  style_dim: 128
optimizer_params:
  bert_lr: 1.0e-05
  ft_lr: 1.0e-05
  lr: 0.0001
preprocess_params:
  spect_params:
    hop_length: 300
    n_fft: 2048
    win_length: 1200
  sr: 24000
pretrained_model: /workspace/ai/jhyoo/StyleTTS2/Models/Multi/0218_TEST/epoch_2nd_00024.pth
save_freq: 1
second_stage_load_pretrained: true
slmadv_params:
  batch_percentage: 0.5
  iter: 10
  max_len: 500
  min_len: 400
  scale: 0.01
  sig: 1.5
  thresh: 5
plbert_params:
  vocab_size: 179
  hidden_size: 768
  num_attention_heads: 12
  intermediate_size: 2048
  max_position_embeddings: 512
  num_hidden_layers: 12
  dropout: 0.1
asr_params:
  input_dim: 80
  hidden_dim: 256
  n_token: 179 
  token_embedding_dim: 256